version: "3.7"

services:
  unitystation:
    image: unitystation/unitystation:develop
    ports:
      - 7777:7777
    environment:
      HUB_USERNAME: $HUB_USERNAME
      HUB_PASSWORD: $HUB_PASSWORD
      SERVER_NAME: Unitystation - EU02 Staging
      ERROR_WEBHOOK: $ERROR_WEBHOOK
      OOC_WEBHOOK: $OOC_WEBHOOK
      ANNOUN_WEBHOOK: $ANNOUN_WEBHOOK
    labels:
      - io.portainer.accesscontrol.public
    volumes:
      - /root/admin:/server/Unitystation_Data/StreamingAssets/admin
